<a href="https://colab.research.google.com/github/sinarazi/Self_learning_files/blob/main/NumPy(P5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 5
Let's recap :)

In [1]:
import numpy as np

In [3]:
# lets define simple numpy array
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

## Why numpy rathar than python?
Numpy package provides state-of-the-art mathmatcial methods so as to be developed in statistics, linear algebra and many other things. In comparison with python, it is really fast, and somehow handle the python's slow pace when it comes to heavy parallel calculations  

# How to create an array from existing data

### numpy.asarray

This appraoch is used to create an array by using the existing data in the form of lists, or tuples. This routine is useful in the scenario where we need to convert a python sequence into the numpy array object.

The syntax to use the asarray() routine is given below.

```numpy.asarray(sequence,  dtype = None, order = None)  ```

It accepts the following parameters.

1) sequence: It is the python sequence which is to be converted into the python array.

2)dtype: It is the data type of each item of the array.

3)order: It can be set to C or F. The default is 

In [15]:
import numpy as np  

l = [1, 2, 3, 4, 5, 6, 7]  
a = np.asarray(l);  
print(type(a))  
print(a) 

#------------------------------------

l1 = [[1, 2, 3, 4, 5, 6, 7],[8, 9]]  
a1 = np.asarray(l1);  
print(type(a1))  
print(a)  

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  # This is added back by InteractiveShellApp.init_path()


### numpy.frombuffer
This function is used to create an array by using the specified buffer. The syntax to use this buffer is given below.

```numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)```  
It accepts the following parameters.

- buffer: It represents an object that exposes a buffer interface.
- dtype: It represents the data type of the returned data type array. The default value is 0.
- count: It represents the length of the returned ndarray. The default value is -1.
- offset: It represents the starting position to read from. The default value is 0.

In [6]:
l = b'hello world'  
print(type(l))  
a = np.frombuffer(l, dtype = "S1")  
print(a)  
print(type(a)) 

<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


### numpy.fromiter
This routine is used to create a ndarray by using an iterable object. It returns a one-dimensional ndarray object.

The syntax is given below.

```numpy.fromiter(iterable, dtype, count = - 1)  ```

It accepts the following parameters.

- Iterable: It represents an iterable object.
- dtype: It represents the data type of the resultant array items.
- count: It represents the number of items to read from the buffer in the array.

In [7]:
list = [0, 2, 4, 6]  
it = iter(list)  
x = np.fromiter(it, dtype = float)  
print(x)  
print(type(x))  

[0. 2. 4. 6.]
<class 'numpy.ndarray'>


## Let's make a new numpy array from existing array :)

These methods ```np.vstack(), np.hstack(), np.hsplit(), .view(), copy()``` will be covered in this part.

let's define an array as below.

In [10]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
# the index that you wanna slice your array should be defined
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [11]:
# let's define two other numpy array
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

These two arrays can comforatably be stacked by these methods.

- ```np.vstack()``` : You can stack them vertically with vstack

- ```np.hstack() ``` : Or stack them horizontally with hstack

In [13]:
np.vstack((a1, a2)) # vertical stack

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [14]:
np.hstack((a1, a2)) # horizontal stack|

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## Basic array operations

## Broadcasting

## More useful array operations

## Acknowledgement:
Thanks for your stata-of-the-art documents
- [Numpy](https://numpy.org/doc/stable/user/absolute_beginners.html)
- [javatpoint](https://www.javatpoint.com/numpy-array-from-existing-data)